### ISSUE TITLE
Exception while trying to import an airodump file

### ISSUE THREAD

**Issue by Calibanda** [ivre/ivre#1146]
### IVRE Version

```
root@ivreclient:/# ivre version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.16.dev221

Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]

Linux ivreclient 5.10.42-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021 x86_64

Dependencies:
    Python module pymongo: 3.7.1
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 2.6.1
    Python module krbV: missing
    Python module PIL: 5.4.1
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: 19.0.0
    Python module tinydb: missing

```

### Summary

When I use the command ivre airodump2db this a airodump csv result, IVRE returns a Python exception

### Expected behavior

I'd expected to import my airodump csv file to the mongodb database to visualize captured Wi-Fi hotspots in the IVRE web interface.

### Actual behavior

IVRE returns this Python exception:

```python
root@ivreclient:/# ivre airodump2db ivre-share/airodump/airodump-01.csv 
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 103, in <module>
    main()
  File "/usr/local/bin/ivre", line 71, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.7/dist-packages/ivre/tools/airodump2db.py", line 88, in main
    bulk.append("\n".join(query), line)
AttributeError: 'BulkOperationBuilder' object has no attribute 'append'

```

### How to reproduce

1. Install IVRE on Docker from GitHub repository.
2. Generate a csv airodump output file:

```bash
$ sudo airodump-ng wlp0s20f3 --write airodump --output-format csv
```
3. Import the csv file in the IVRE CLI:
```bash
root@ivreclient:/# ivre airodump2db ivre-share/airodump/airodump-01.csv
```

### More

Please find attached the csv output file that I tried to upload. Note that I needed (for confidentiality reasons) to hide all SSIDs but the exception happened before this anonymization.
[airodump-01.csv](https://github.com/ivre/ivre/files/6807773/airodump-01.csv)

Thank you very much for your help!

**Comment by p-l-** [comment]
Hi,
Thanks for your interest in IVRE.
I must say I am not really surprised that a bug exists here, because this tool is not used (and probably not tested either).
I'll have a look and let you know.

**Comment by p-l-** [comment]
The code in `airodump2db` has not been migrated to the recent backends (MongoDB or TinyDB -based), and uses hardcoded Neo4j queries...

**Comment by p-l-** [comment]
Hi, sorry for the delay.

After a deeper look, it seems that the insertion of Airodump logs into the `flow` purpose is probably not something that matches how that purpose is now used: we used to have both "flow" and "node" information, and we now only have "flow" information (the "node" information should probably be stored in "scans" or "passive").

@Calibanda could you explain what you wanted to do with this log file inserted? Was it just for random tests or did you have any specific usage in mind?

Thanks and sorry for that bug.

**Comment by Calibanda** [comment]
Hi,

We plan to use IVRE in an industrial environment and were testing all its functionalities before using it in production.
I was testing all commands one by one and thought I could use `airodump2db` to visualize scanned Wi-Fi hotspots in the same graphical way as `flow` or the nmap xml results.

What was the original objective of this function? Unfortunately, I didn't find the documentation of this command.

Please don't apologize, I understand all the complications around open-source projects.

**Comment by p-l-** [comment]
In that case, I think your best option would be to use Zeek against the PCAP capture files produced by Airodump-ng, and then to use `ivre zeek2db` on the log files produced by Zeek.

You can also use the Zeek files provided by IVRE (the `zeek/ivre` directory in the sources, the `[PREFIX]/share/ivre/zeek/ivre` directory when IVRE has been installed), to produce two more logs: `arp.log` and `passive_recon.log`; the first one will be processed using `ivre zeek2db`, as the other ones, and the second one will be processed by `ivre passiverecon2db` and will feed the `passive` purpose (see https://doc.ivre.rocks/en/latest/overview/principles.html#purposes).

**Comment by p-l-** [comment]
With #1156, you can process Airodump logs again, but the data will be stored in the `passive` purpose, as explained in my previous message.

Please re-open if you don't think the issue is fixed.
