### ISSUE TITLE
Hardware recommendation

### ISSUE THREAD

**Issue by 0l4y4** [ivre/ivre#1167]
Hello!

I would like to know what hardware requirements I would need to install ivre.

Thanks

**Comment by p-l-** [comment]
Hi,

There is no such thing as it highly depends on the amount of data you are going to process, the kind of requests your users will make, and the number of users.

In the end, it is mostly a question about the database server (even though the server used for result insertion / view creation might also be important for very large results).

I would suggest you ask this question on a MongoDB forum or to their support.

All the best!
