### ISSUE TITLE
Implement sort & fields in HTTP backend

### ISSUE THREAD

**Issue by p-l-** [ivre/ivre#1195]
The HTTP backend is correctly usable **but** lacks an important feature: sorting results (the sort & fields parameters are discarded). See `# TODO: sort` comments in `ivre/db/http.py`.

**Comment by priyadarshan1995** [comment]
can this be worked on?

**Comment by p-l-** [comment]
@ChandanChainani Nope, it would be closed if so!

**Comment by p-l-** [comment]
`sort=` should be OK now (#1212). `fields=` still needs to be worked on.
