### ISSUE TITLE
Nuclei scans import in Ivre

### ISSUE THREAD

**Issue by itnsec** [ivre/ivre#1203]
Hi, first, thanks for Ivre, it's a great product ! 

### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.16.dev328

Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0]

Linux ivre 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64

Dependencies:
    Python module pymongo: 3.10.1
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 2.8
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.2.0
    Python module MySQLdb: missing
    Python module dbus: 1.2.16
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: 19.0.0
    Python module tinydb: missing

$ nuclei version
[INF] Using Nuclei Engine 2.5.3 (latest)
[INF] Using Nuclei Templates 8.6.1 (latest)
```

### Summary

I tried to import nuclei scans results, but it reaches an error of parsing. 

### Expected behavior

Import the Nuclei json file to database.

### Actual behavior

Unable to parse the Nuclei json file. 

### How to reproduce

Nuclei scan generated by : 
```
$ nuclei -u http://1.2.3.4/ -t exposures/files/ds_store.yaml -json -o nuclei.json
```

Ivre import : 
```
$ ivre scan2db -c nuclei -s nuclei nuclei.json
WARNING:ivre:Exception (file 'nuclei.json')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 1909, in store_scan
    store_scan_function = {
KeyError: b'{'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/scan2db.py", line 145, in main
    if database.store_scan(
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 1938, in store_scan
    raise ValueError("Unknown file type %s" % fname)
ValueError: Unknown file type nuclei.json
INFO:ivre:0 results imported.
```

### More

Both ivre and nuclei are on lastest versions.

If i miss somethings, please let me know.

Sample of nuclei json file : 
```
{"template-id":"ds-store-file","info":{"name":"Directory Listing via DS_Store","author":["0w4ys"],"tags":["exposure"],"reference":null,"severity":"info"},"type":"http","host":"http://1.2.3.4/","matched-at":"http://1.2.3.4/.DS_Store","timestamp":"2021-10-29T04:47:12.288959197Z","curl-command":"curl -X 'GET' -d '' -H 'Accept: */*' -H 'Accept-Language: en' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36' 'http://1.2.3.4/.DS_Store'"}
```

Thanks for your help,
Bests regards

**Comment by itnsec** [comment]
Thanks @0xtavian !

**Comment by p-l-** [comment]
Thanks for reporting @itnsec, and thanks for your help @0xtavian!

#1206 should fix this issue.

**Comment by itnsec** [comment]
Many thanks for fixing so fastly. 
Is there a way (or workaround) to map nuclei's scanned domains with IP in ivre ?

WARNING:ivre:Hostnames in URL not supported ['https://<url>']
i would like to avoid to sed domain with ip, because there could be severals virtual hosts with different vulns on the same ip.

**Comment by p-l-** [comment]
Unfortunately no. Recent nuclei versions should report the `id` field in HTTP template results, and future nuclei versions will, I hope, do the same for other results (e.g., network templates).

**Comment by p-l-** [comment]
I just realize your sample has no `ip` field **and** you mention you are using the latest Nuclei version. This is weird, because the `ip` field should be included. Can you confirm the Nuclei version you are using @itnsec?

**Comment by itnsec** [comment]
nuclei --version
[INF] Current Version: 2.5.3

**Comment by p-l-** [comment]
Thanks for your answer. Actually this is a regression in Nuclei; I'm currently `git bissect`-ing to find out what happened.
