### ISSUE TITLE
New Install - using Fast install

### ISSUE THREAD

**Issue by jimthedj65** [ivre/ivre#1216]
### IVRE Version

```
$ ivre version (generates an error after install)
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.16

Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] 

VERSION="18.04.6 LTS (Bionic Beaver)"

Dependencies:
asn1crypto (0.24.0)
bottle (0.12.19)
certifi (2021.10.8)
cffi (1.15.0)
cryptography (3.3.2)
elasticsearch (7.15.2)
enum34 (1.1.6)
idna (2.6)
ipaddress (1.0.17)
keyring (10.6.0)
keyrings.alt (3.0)
pip (9.0.1)
psycopg2 (2.8.6)
pycparser (2.21)
pycrypto (2.6.1)
pygobject (3.26.1)
pyOpenSSL (21.0.0)
pyxdg (0.25)
SecretStorage (2.3.1)
setuptools (39.0.1)
six (1.11.0)
SQLAlchemy (1.1.11)
tinydb (3.15.2)
urllib3 (1.26.7)
wheel (0.30.0)
    [...]
```

### Summary

I installed all as expected with 
'$ sudo apt -y --no-install-recommends install mongodb python3-pymongo \
>   python3-crypto python3-bottle apache2 libapache2-mod-wsgi-py3 dokuwiki
$ git clone https://github.com/ivre/ivre
$ cd ivre
$ python3 setup.py build
$ sudo python3 setup.py install'

and when I try to run ivre version on the command line I get an error
`Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 39, in <module>
    from ivre import utils, tools  # noqa: E402
  File "/usr/local/lib/python3.6/dist-packages/ivre/utils.py", line 2136, in <module>
    def _parse_subject(subject: osslc.X509Name) -> Tuple[str, Dict[str, str]]:
NameError: name 'osslc' is not defined`

**I followed up with installing ivre on the cli with pip and it started to work?**

### Expected behavior

Version of ivre should show.   Web pages loads fine. 
### Actual behavior

I checked apache2 logs and found 
`NameError: name 'osslc' is not defined, referer:`

### How to reproduce

ivre version (generates an error, but downloaded today)

any help to rectify the build on a baremetal Ubuntu 18.04

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this. You need to install the package `python3-openssl`, it is missing from the documentation; I'll update it.

**Comment by jimthedj65** [comment]
thank you makes sense.
