### ISSUE TITLE
Modbus Demo Data 2015 import for 0.9.16

### ISSUE THREAD

**Issue by jimthedj65** [ivre/ivre#1229]
### IVRE Version
```
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.16

Python 2.7.17 (default, Feb 27 2021, 15:10:58)
[GCC 7.5.0]

Linux  4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64

Dependencies:
    Python module pymongo: 3.12.1
    Python module sqlalchemy: 1.1.11
    Python module psycopg2: 2.8.6 (dt dec pq3 ext lo64)
    Python module cryptography: 3.3.2
    Python module krbV: 1.0.90-1 **[reports unknown]**
    Python module PIL: 6.2.2
    Python module MySQLdb: missing
    Python module dbus: 1.2.6
    Python module matplotlib: 2.2.5
    Python module bottle: 0.12.19
    Python module OpenSSL: 21.0.0
    Python module tinydb: 3.15.2
```

### Summary
Hi Pierre, I tried to install the modbus sample data using `sudo ivre nmap2db Nmap-Modbus-IPv4-screenshots.v4.json.bz2`

I then got a `INFO:ivre:0 results imported.`

### Expected behavior

Data will be imported and will be visible on the gui

### Actual behavior

no import

### How to reproduce

Q. Is it still possible to use the sample data ? or do you have an updated version?

Thanks in advance

**Comment by p-l-** [comment]
Hi,

Is it possible that the scan already exists in the database? A scan cannot be inserted twice. Can you run `ivre scancli --count`?

**Comment by jimthedj65** [comment]
Hi Pierre,

I got distracted with work sorry.  I am not sure what happened but the sample data appeared after I imported another scan.  it is possible that I inserted it twice and didn't catch it the first time.

Seems ok now; I may purge the data and try again and see what happens.

**Comment by jimthedj65** [comment]
Hi Pierre,

From a blank DB I ran the command 
`ivre scan2db Nmap-Modbus-IPv4-screenshots.v4.json.bz2` 

I then got the error, showing below and it reports **INFO:ivre:0 results imported**. but when I run `ivre scancli --count` it shows a count of 3184 which has imported a ton of records

```
WARNING:ivre:Exception (file 'Nmap-Modbus-IPv4-screenshots.v4.json.bz2')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ivre/tools/scan2db.py", line 127, in main
    zgrab_port=args.zgrab_port,
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1792, in store_scan
    return store_scan_function(fname, filehash=scanid, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1877, in store_scan_json_ivre
    self._schema_migrations["hosts"][oldvers][1](host)
  File "/usr/local/lib/python2.7/dist-packages/ivre/db/__init__.py", line 1152, in __migrate_schema_hosts_13_14
    script["ls"]
  File "/usr/local/lib/python2.7/dist-packages/ivre/xmlnmap.py", line 588, in change_ls_migrate
    for fileentry in volume.get('files', []):
AttributeError: 'NoneType' object has no attribute 'get'
INFO:ivre:0 results imported.
```

hope it helps

**Comment by p-l-** [comment]
That is weird indeed, and this is a bug. Thanks for reporting it!

**Comment by p-l-** [comment]
Should work fine if you upgrade to current master.

**Comment by jimthedj65** [comment]
perfect thanks

**Comment by jimthedj65** [comment]
Hi Pierre,

I got some warnings after the update 
`INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Windows 7 Home Premium 7601 Service Pack 1'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Windows Server 2008 R2 Foundation 7600'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Windows Server 2008 R2 Standard 7600'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Windows 7 Home Premium 7601 Service Pack 1'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Windows Server 2008 R2 Standard 7600'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'
INFO:ivre:New OS not yet registered in WINDOWS_VERSION_TO_BUILD 'Unix'

INFO:ivre:1 results imported.`

I then run ivre scancli --count and get 12k of imports.

hope it helps

**Comment by p-l-** [comment]
That's normal; so everything works fine.

**Comment by jimthedj65** [comment]
yes all working fine now thanks for clarifying that the errors are normal.

**Comment by p-l-** [comment]
They are not errors by the way, but `INFO` messages.
