### ISSUE TITLE
Add Custom CLI Tools (Enumeration focus)

### ISSUE THREAD

**Issue by WesWrench** [ivre/ivre#1245]
Hello,

I wanted to know if it was possible to add another cli command to the tool (easily) in order to add other tools like:
- https://github.com/rverton/webanalyze (for the analysis of fingerprints in the HTML code)

Or for example adding feed like:
- crt.sh, facebook certificate transparency monitoring, securitytrails, domaintools ...

The goal would be to have a more verbose part for HTTP / HTTPs services.
In addition there are many other enumerations tools more exhaustive than nmap for specific services (https://book.hacktricks.xyz/external-recon-methodology / https://guide.offsecnewbie.com/network-pen).

Concerning the DNS Records Monitoring, is there a simple way to add simple feature (with a cli) that detect the high availability algorithm (Round Robin DNS, Network Round Robin, No High Availability Detected, ...) by analyzing DNS results ?

Best regards,

**Comment by p-l-** [comment]
Hi,

Could you be more specific: for example, could you show what you would like to do (what options you would enter, what result IVRE would give)?

About your second question: first, your questions are better asked on [Gitter](https://gitter.im/ivre/ivre) than on an unrelated issue (if issues work better for you, open another one). Apart from that, the results are stored in the database, and for now no tool exist to analyse them the way you want (but I'd love such a contribution!)

**Comment by WesWrench** [comment]
Hello,

I read the code and what is problematic is the lack of modularity.
To add a new source of logs, you must add .py file(s) to the root of the drunk folder and modify other files.

It would be a bit like "OpenCTI" to have a "connector" vision where we only design the data format and the "converter" to standardize the data.

At the same time, I sent you an email to get access to the demo version.

Best regards,

**Comment by p-l-** [comment]
OK so maybe you can use the demo / install an instance and re-open this issue when you have more specific ideas about what you want to add?

Happy hacking!
