### ISSUE TITLE
[Demo Account] Ivre.rocks

### ISSUE THREAD

**Issue by WesWrench** [ivre/ivre#1308]
Hello,

I lost the demo account you sent me.
I sent you an email (in French) to ask you again.
In the absence of return, I allow myself to open this issue.
Would you like me to resend the email to you in English?
In this email I also provided you with  TXT records list allowing you to do technology recognition (often saas).

Best regards,

**Comment by p-l-** [comment]
Hi,

Sorry for the delay in email answers, anyway the demonstration instance is not handled here so I'm closing this issue. I'll come back to you as soon as I have some time.

All the best,

Pierre
