### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by fox4914** [ivre/ivre#1341]

**Comment by fox4914** [comment]
**What am I doing wrong? The Web UI does not output the result. Where and what is missing?**

_**The "HELP" tab :**_
```
Forbidden

You don't have permission to access this resource.
Apache/2.4.52 (Debian) Server at localhost Port 80
```
_**When importing via the terminal:**_
```
WARNING:ivre:Cannot find file [tor_exit_nodes.txt]. Try running `ivre getwebdata`
INFO:ivre:7 results imported.
```
_**INFO:**_
```
ivre version
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.17.dev263

Python 3.9.10 (main, Jan 16 2022, 17:12:18) 
[GCC 11.2.0]

Dependencies:
    Python module pymongo: 4.1.1
    Python module sqlalchemy: 1.4.23
    Python module psycopg2: 2.9.2 (dt dec pq3 ext lo64)
    Python module cryptography: 3.4.8
    Python module krbV: missing
    Python module pycurl: PycURL/7.44.1 libcurl/7.81.0 GnuTLS/3.7.4 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.4.59
    Python module PIL: 9.0.0
    Python module MySQLdb: 1.4.6
    Python module dbus: 1.2.18
    Python module matplotlib: 3.5.1
    Python module bottle: 0.12.19
    Python module OpenSSL: 21.0.0
    Python module tinydb: 4.7.0
```
**Thanks**

**Comment by p-l-** [comment]
Hi,

> The "HELP" tab :

See https://doc.ivre.rocks/en/latest/overview/faq.html#notebook-shows-forbidden.

> When importing via the terminal:

As explained in the warning message, you an run `ivre getwebdata` before importing results.

Also, the IVRE Web UI displays the results from the "view" purpose, and you have only inserted results in the "scan" (or "nmap" purpose. See https://doc.ivre.rocks/en/latest/overview/principles.html#purposes. You need to run `ivre db2view` to create / update the view using scan or passive results.

Hope this helps,

Pierre

**Comment by p-l-** [comment]
Please reopen if you still have an issue.
