### ISSUE TITLE
httpx save the scan document scanner description error

### ISSUE THREAD

**Issue by ck00004** [ivre/ivre#1345]
https://github.com/ivre/ivre/blob/1b4e0125a129b3fb5292e62a7bcafd73fd6fc915/ivre/db/__init__.py#L3114
https://github.com/ivre/ivre/blob/1b4e0125a129b3fb5292e62a7bcafd73fd6fc915/ivre/db/__init__.py#L3237

store_scan_json_httpx and store_scan_json_nuclei function The same store_scan_doc parameters are used

**Comment by p-l-** [comment]
Nice catch, thanks for reporting this!
