### ISSUE TITLE
Duplicate entries in view

### ISSUE THREAD

**Issue by aretsmarvin** [ivre/ivre#1357]
### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.17.dev274

Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]

Linux ubuntu 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64

Dependencies:
    Python module pymongo: 3.10.1
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 2.8
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: 1.2.16
    Python module matplotlib: missing
    Python module bottle: 0.12.15
    Python module OpenSSL: 19.0.0
    Python module tinydb: missing

```

### Summary

IVRE (sometimes?) creates duplicate entries in the view, for the same IP address (and port).
I am running Nmap scans via my own Python script, then I import those scans (from XML).

### Expected behavior

Single entry per IP address in the web UI.

### Actual behavior

Duplicate entries:
![afbeelding](https://user-images.githubusercontent.com/45003967/169252303-73517f42-5f02-4788-99fa-3e96d3b49cc3.png)

### How to reproduce

I run the Nmap scan:
`nmap --script=auth -sV -p 80 -T4 --host-timeout 60m -oX file.xml`
Then I import this scan:
`ivre scan2db -c NetFlow -r FOLDERNAME`
`ivre db2view nmap --category NetFlow`

### More

I can't say exactly why/when it does it. But it looks like it does it only, after a few hours.
I run my scans every hour, and I mention, those duplicate entries come in after some hours (when started with an empty view/database).

It doesn't do it for all entries.

**Comment by p-l-** [comment]
Hi,

This really looks like a bug (and an embarrassing one!). Thanks for this report.

Could you share (here or privately) two scan results that will not merge?

**Comment by aretsmarvin** [comment]
> Hi,
> 
> This really looks like a bug (and an embarrassing one!). Thanks for this report.
> 
> Could you share (here or privately) two scan results that will not merge?

Hi, where can I share it private? 

And with scan results you mean the XML files of the Nmap scan, right?

**Comment by p-l-** [comment]
OK. Ideally, could you send the XML files to `pl (at) ivre (dot) rocks`?

I'll try to reproduce the exact same steps.

**Comment by p-l-** [comment]
BTW quick question: is it possible that several people (or several processes) are operating on the DB at the same time?

**Comment by p-l-** [comment]
Also, can you report the output of `ivre scancli --count [the IP address]` and `ivre view --count [the IP address]`?

**Comment by aretsmarvin** [comment]
> BTW quick question: is it possible that several people (or several processes) are operating on the DB at the same time?

Oh Yes. Forgot to mention. My python scanner does multiple scans (hosts) at the same time, and when a scan (host) is finished, it imports it directly. This could be at the same time.

**Comment by p-l-** [comment]
That should not be a problem. What I meant was several `db2view` at the same time. But maybe a `db2view` while a `scan2db` is running could be the cause.

**Comment by aretsmarvin** [comment]
> That should not be a problem. What I meant was several `db2view` at the same time. But maybe a `db2view` while a `scan2db` is running could be the cause.

Both could be the case. The db2view and scan2db are ran sequentially, for the same ip.
But they can cross each other for different IP’s.

**Comment by p-l-** [comment]
OK so maybe you could to add some kind of lock to prevent a `db2view` from occurring while another `db2view` or `scan2db` is running for the same IP?

**Comment by aretsmarvin** [comment]
They will not run for the same IP at once. 
Like, for the same IP, I always first run scan2db and then db2view.

If the commands simultaneously it is only for different IP’s.

**Comment by p-l-** [comment]
I had a look at your code and there is something you could (should?) do, I think: you run `ivre scan2db` on a file containing, if I understand well, results for one specific IP, and run `db2view` just after that. But you run `db2view`against all the collection.

The `ivre db2view` does not need the `--category` parameter (to be clear: it will not add the category to the result in view, but will only select results from the scans that have this category), but you should add `--host [ip address]`; this would ensure that the `db2view` only affects results for the specific IP address. If, as I suspect, this issue is a kind of race condition, that may be enough.

Also, since IVRE happens to be a Python project, just like your tool, you could use the Python API rather than calling the CLIs.

Let me know if I can help. You may want to join [the gitter channel](https://gitter.im/ivre/ivre).

**Comment by p-l-** [comment]
And by the way, you may want to have a look at the agents in IVRE for your project. I'm not certain but it might help you.

**Comment by p-l-** [comment]
> The `ivre db2view` does not need the `--category` parameter (to be clear: it will not add the category to the result in view, but will only select results from the scans that have this category), but you should add `--host [ip address]`; this would ensure that the `db2view` only affects results for the specific IP address. If, as I suspect, this issue is a kind of race condition, that may be enough.

Actually, there is a better way, which is to use `--update-view` in the `ivre scan2db` command. You don't need to run `db2view` with that (I had totally forgotten that option because I never use it!). See aretsmarvin/FlowScanner#2.

**Comment by aretsmarvin** [comment]
@p-l- thanks! The `--update-view` option seems to solve the issue. 
I've merged your pull request. 

> Also, since IVRE happens to be a Python project, just like your tool, you could use the Python API rather than calling the CLIs.
Yes, I am aware of that, and was planning to change that indeed. 

Thanks for the good and quick help :)
