### ISSUE TITLE
Blank screenshot with phantomjs

### ISSUE THREAD

**Issue by psyray** [ivre/ivre#1397]
### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18.dev25-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Linux 2f86dcf6bc91 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing

```

### Summary

I use the latest docker version and I have a problem with screenshot on https website.
Screenshot is blank.

I tried to launch phantomjs from command line, same issue.

### Expected behavior

Screenshot for https website should work with the docker install

### Actual behavior

After launching phantomjs from command line
```
phantomjs --ignore-ssl-errors=true --debug=true google.js
```
config.js
```js
var system = require('system');
var webpage = require('webpage');
function capture(url, fname) {
    var page = webpage.create();
    page.open(url, function() {
        page.viewportSize = {
            width: 1024,
            height: 768
        };
        page.evaluate(function(){
            document.body.bgColor = 'white';
        });
        page.render(fname, {format: 'jpeg', quality: '90'});
        phantom.exit();
    });
}
capture("https://www.google.fr:443", "screenshot-google.jpg");
setTimeout(phantom.exit, 300 * 1000);
```
It seems to be missing some cipĥer.
```
2022-07-14T19:01:06 [DEBUG] Network - Resource request error: 99 ( "Invalid or empty cipher list (error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match)" ) URL: "https://www.easi-services.fr/" 
```

I've updated phantomjs to 2.1.1 (it was 1.9.8)
Added a little workaround to not use openssl3 because of error at start
https://github.com/bazelbuild/rules_closure/issues/351
```
export OPENSSL_CONF=/dev/null
```
https://github.com/bazelbuild/rules_closure/issues/351#issuecomment-854628326

And now it's working, I always need to add this parameter when launching phantomjs from the command line
```
--ignore-ssl-errors=true
```

### How to reproduce

Launch a scan on https website, screenshot is blank

**Comment by p-l-** [comment]
Hi there!

Thanks a lot for this detailed report. Do you feel like you would like to create a PR that fixes it (since you have understood what is needed; I can assist you on that), or not (I can probably find some time to create the fix myself)?

PIerre
