### ISSUE TITLE
Content hidden by CSS max-height rule in host list

### ISSUE THREAD

**Issue by psyray** [ivre/ivre#1398]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18.dev25-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]

Linux 2f86dcf6bc91 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing

```

### Summary

Due to a CSS max-height value, content is hidden in the host list

### Expected behavior

See full content in the box

### Actual behavior

Content hidden

### How to reproduce

List host with a lot of content

### More

With max-height
![image](https://user-images.githubusercontent.com/1230954/179211288-8c78d2bf-406d-4440-98ef-1adff877a61c.png)

Without
![image](https://user-images.githubusercontent.com/1230954/179211197-736e4448-39c2-449d-bd08-1a2d7eff27d4.png)

**Comment by p-l-** [comment]
This is meant to avoid a "summary" that would use too much space. You can see that I am far from being a frontend dev :)

Feel free to submit a PR if you feel like it should change.

**Comment by psyray** [comment]
I understand ;)
And I think this could be enhanced, I will have a look and submit a PR ;)
And I will also enhanced the display for the Explore View.
If label is too large we can't see them
![image](https://user-images.githubusercontent.com/1230954/179405472-351c8bb1-9b1c-4dd7-a77d-e069a29c1245.png)

**Comment by psyray** [comment]
> This is meant to avoid a "summary" that would use too much space. You can see that I am far from being a frontend dev :)
> 
> Feel free to submit a PR if you feel like it should change.

Instead of putting an `overflow: hidden`, I could pout an `overflow: scroll` in the ivre.css, line 142
With that we could scroll the entire list, in preview mode, and if a box content overflow it shows a scroll, and we could scroll inside this huge box.
So, this way, no information is lost in preview mode

What do you think of this ?

Result is 
![image](https://user-images.githubusercontent.com/1230954/179411081-cd307a9d-8a87-48a0-bcad-8bdab43f8752.png)
