### ISSUE TITLE
Can't download censys webdata file - 403 error

### ISSUE THREAD

**Issue by psyray** [ivre/ivre#1400]
### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18.dev25-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Linux 2f86dcf6bc91 4.9.0-19-amd64 #1 SMP Debian 4.9.320-2 (2022-06-30) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing
```

### Summary

When launching the `ivre getwebdata` a 403 erreor is returned for censys

```
# ivre getwebdata  
ERROR:ivre:Cannot download https://support.censys.io/hc/en-us/articles/360043177092-from-faq [HTTP Error 403: Forbidden]
```

### Expected behavior

Correctly download web data without errors

### Actual behavior

403 error

### How to reproduce

Launch the above command

I'm trying to find the correct url

**Comment by psyray** [comment]
URL seems to be good, I don't understand wyh a 403 error is returned
I'm tryin' to debug

**Comment by p-l-** [comment]
It seems to depend on the origin of the request: it's downloaded just fine from my broadband connection but I get the 403 error from a server hosted by OVH.

You may want to download the file from your home connection and scp it.

**Comment by psyray** [comment]
Ok thanks, I suspect a block like this, thanks for testing
