### ISSUE TITLE
rtsp-screenshot.nse doesn't save screenshot

### ISSUE THREAD

**Issue by zorrobyte** [ivre/ivre#1431]
Greetings,

I am attempting to use rtsp-screenshot.nse with IVRE, all seems to go well, other than the screenshot actually being saved. I have patched rtsp-url-brute.nse. I can find my camera's routes, it's accessible, but nothing else seems to happen.

ffmpeg is installed on my machine and is working.

`nmap -n -p 554 --script rtsp-screenshot,rtsp-url-brute 10.0.0.4`

I do not yet know enough about nmap's script language to try and update these scripts myself; I may try sometime later

**Comment by xMario0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by p-l-** [comment]
Hey @zorrobyte!
Can you share the full output of the Nmap command?

PS: enjoy your holiday @xMario0!

**Comment by p-l-** [comment]
Inactivity, please reopen if needed
