### ISSUE TITLE
censys.io throws 403 when loading their list of scanners

### ISSUE THREAD

**Issue by gallypette** [ivre/ivre#1437]
### IVRE Version

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18

Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]

Linux ivre 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64

Dependencies:
    Python module pymongo: 4.2.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 38.0.1
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: missing
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.23
    Python module OpenSSL: 22.1.0
    Python module tinydb: missing
```

### Summary

Censys.io throws a 403 when try to download 'https://support.censys.io/hc/en-us/articles/360043177092-from-faq'

### Expected behavior

Get censys_net_extractor to get the list of censys's scanners.

### Actual behavior

ERROR:ivre:Cannot download https://support.censys.io/hc/en-us/articles/360043177092-from-faq [HTTP Error 403: Forbidden]

### How to reproduce

`ivre getwebdata`

### More

I tried to modify the User-Agent in `utils.py` with the one from firefox to no avail: it still throws a 403 while I can reach the page with the web browser.

Any ideas?

**Comment by p-l-** [comment]
Censys is known to block downloads from "server" / "non ISP" ranges. Can you check from your home connection?

**Comment by gallypette** [comment]
But servers are my home  :)
I tried through a free.fr endpoint via VPN without any luck, so I downloaded the file and created the list by hand.

**Comment by p-l-** [comment]
That's weird. So you could access the page and, from the same IP, could not download it with IVRE CLU?

**Comment by gallypette** [comment]
yes, that's why I fiddled with the user agent.t

**Comment by p-l-** [comment]
OK that's weird, I never had that.

**Comment by p-l-** [comment]
That's new (I think): they are now protected by CloudFlare to prevent bots from fetching this page. I'll host a copy somewhere as a workaround, since I have not been able to find this data elsewhere.

**Comment by e-Euler** [comment]
same issue

**Comment by PyroFilmsFX** [comment]
> That's new (I think): they are now protected by CloudFlare to prevent bots from fetching this page. I'll host a copy somewhere as a workaround, since I have not been able to find this data elsewhere.

Where you able to host this?

**Comment by p-l-** [comment]
That's not done yet. I will do it eventually but I must say it's not my top priority at the moment.

**Comment by kaitallaoua** [comment]
also have the same issue

**Comment by wawaloll** [comment]
nuclei got replaced with `https://projectdiscovery.io/` , maybe that's why. hope they'll fix the issue

**Comment by p-l-** [comment]
PR #1620 implements a workaround for this.
