### ISSUE TITLE
Docker Installation / No Screenshots of services

### ISSUE THREAD

**Issue by jallphin** [ivre/ivre#1439]
### IVRE Version

```
# ivre version
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18.dev83-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Linux 39fe6d287a4c 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing

```

### Summary

IVRE does not appear to be taking screenshots, at all. I see the relevant scripts in the `ivreclient` container, in:
```
root@39fe6d287a4c:/usr/local/share/ivre/patches/nmap/scripts# ls -latr
total 44
-rw-rw-r-- 1 root root 2013 Sep 13 09:50 x11-screenshot.nse
-rw-rw-r-- 1 root root 9564 Sep 13 09:50 vnc-screenshot.nse
-rw-rw-r-- 1 root root 2928 Sep 13 09:50 rtsp-screenshot.nse
-rw-rw-r-- 1 root root 2792 Sep 13 09:50 mainframe-screenshot.nse
-rw-rw-r-- 1 root root 1751 Sep 13 09:50 mainframe-banner.nse
-rw-rw-r-- 1 root root 4181 Sep 13 09:50 http-screenshot.nse
drwxr-xr-x 3 root root 4096 Sep 13 12:10 ..
drwxr-xr-x 2 root root 4096 Sep 13 12:10 .
```

PhantomJS is also installed but there appears to be an issue with it:
```
root@39fe6d287a4c:/# phantomjs -h
Auto configuration failed
140112941868992:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140112941868992:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140112941868992:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140112941868992:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
```

### Expected behavior

IVRE should be taking screenshots of relevant webservices, but it is not. 

### Actual behavior

No screenshots are being produced. 

### How to reproduce

Install via docker. 

### More

Could this be an issue where docker is a few versions behind any commits you've made to fix this problem? I recall it used to work in docker a couple months ago. If there is a configuration issue, please let me know what I need to add into `ivre.conf` to enable screenshots. Thanks! Also, kickass work so far!

**Comment by p-l-** [comment]
Hi!

Thanks for reporting this. It has not been fixed so far. I believe it comes from phantomjs binary incompatibility with the Debian used as a base for the IVRE Docker images.

I'll have a look soon.

**Comment by p-l-** [comment]
Problem identified, and hopefully solved. When the PR is merged, we will still have to wait for the fresh Docker images. I'll keep you posted here.

**Comment by jallphin** [comment]
Great! Thanks Pierre, great work so far!!

**Comment by p-l-** [comment]
New images have been pushed @jallphin. If you can test and report here if it's OK or not that would be great!
