### ISSUE TITLE
Easy Setup

### ISSUE THREAD

**Issue by DeadlyyRage** [ivre/ivre#1443]
I'm on Parrot OS 5.1 and I'm having trouble setting up IVRE and using the Web UI along with the scan2db and the requirements. I was wondering if maybe you guys could make a youtube video of setting up IVRE on different OS's. For example, Arch,Cent,Gentoo,Debian,Parrot, etc.

**Comment by p-l-** [comment]
Hi,
That's not planned for now, I'm sorry.
