### ISSUE TITLE
Support for raspberry pi and arm64 devices

### ISSUE THREAD

**Issue by italianconcerto** [ivre/ivre#1452]
Hi, I was wondering if there is any possibility to add a docker compose configuration for arm64 devices like Jetson boards or raspberry pies.

I tried the different guidelines but I couldn't migrate the docker images to an arm version.

**Comment by p-l-** [comment]
Hi, no idea how hard this would be. Probably the hardest part would not be IVRE itself.

Since IVRE is basically only a Python package, and since MongoDB seems to have arm64 packages, you may try to install IVRE using `pip`, and to follow the MongoDB installation guide for the database?

**Comment by italianconcerto** [comment]
If that is so straightforward I'll try by myself

**Comment by italianconcerto** [comment]
![immagine](https://user-images.githubusercontent.com/48441989/198900886-97847f75-a12e-49c1-83b2-1dd537ac41a8.png)

I just installed it but it seems like these packages were not installed. It didn't show any error so I understand if this can work either way

**Comment by p-l-** [comment]
If you need answers to questions please join [Gitter](https://gitter.im). I'll close this issue for now. Please reopen if needed.
