### ISSUE TITLE
How is passive dns suppose to be displayed in the web gui

### ISSUE THREAD

**Issue by Benster134** [ivre/ivre#1491]
### IVRE Version

IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev9

Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0]

Linux kali 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64

Dependencies:
    MySQLdb: 1.4.6
    OpenSSL: 23.0.0
    PIL: 9.3.0
    bottle: 0.12.23
    cryptography: 38.0.4
    dbus: 1.3.2
    krbV: *missing*
    matplotlib: 3.6.3
    psycopg2: 2.9.4 (dt dec pq3 ext lo64)
    pycurl: PycURL/7.45.2 libcurl/7.87.0 GnuTLS/3.7.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.51.0 librtmp/2.3
    pymongo: 3.11.0
    sqlalchemy: 1.4.45
    tinydb: 3.15.2

### Summary

How is Passsive DNS results supose to look like?

### Expected behavior

Expected behaviour is to display dns results and to say it was gathered by zeek.

### Actual behavior

Just get the following output

10.20.26.30(example.com)
UP - passive
Reserved address
MAC Address: <mac address>

### How to reproduce

I have been trying to follow documentation but it seems there is some items missing

$ mkdir logs
$ sudo LOG_PATH=logs/passiverecon \
>   zeek -b /usr/share/ivre/zeek/ivre/passiverecon/bare.zeek -C -i eth0

$ ivre passivereconworker --directory=logs

(root㉿kali)-[/usr/…/zeek/ivre/passiverecon/logs]
└─# ivre zeek2db ./*.log

(root㉿kali)-[/usr/…/zeek/ivre/passiverecon/logs]
└─# ivre flowcli

(root㉿kali)-[/usr/…/zeek/ivre/passiverecon/logs]
└─# ivre db2view
WARNING:ivre:Cannot find file [censys_scanners.txt]. Try running `ivre getwebdata`
WARNING:ivre:Cannot find Maxmind database files

ivre httpd --bind-address 10..20.26.50

### More

I also cant get flow to work using these commands. nothing is displayed in flow

**Comment by p-l-** [comment]
Hey there!

I'd suggest you have a look at this part of the documentation: https://doc.ivre.rocks/en/latest/overview/principles.html#storing-data

As you can see, `ivre zeek2db` will only populate the "flow" purpose, not the passive. The `ivre passiverecon2db` command, with the specific passiverecon log files, will populate the "passive" purpose.

With the "flow" purpose populated, you should see flows when running `ivre flowcli --count`. If that shows some flows, you can open your browser to the `/flow.html` page to use the Web UI (the flow interface is distinct from the main interface).

The "passive" purpose can only be queried with the command line. However, part of it can be converted to elements in the "view" feature (as shown in the schema in the documentation). So if `ivre ipinfo --count` shows that there are some records in the "passive" purpose, you can run `ivre db2view` to populate the "view" purpose. Once done, `ivre view --count` should report some records, and you should be able to use the main page of the Web interface to view them.

Hope this helps!

**Comment by Benster134** [comment]
Good day

Can I get all the passive data with an api call. I want to use one call to get all the passive dns. like ivre ipdata but just for all the hosts that has dns queries?

**Comment by p-l-** [comment]
Hey!

This is a bug tracker, not a forum. Could you ask your next questions on [the chat](https://gitter.im/ivre/ivre)?

You can try: `ivre iphost //` (the `//` is a regexp that will match anything).
