### ISSUE TITLE
improve performance db2view

### ISSUE THREAD

**Issue by merinet** [ivre/ivre#1496]
### Discussed in https://github.com/ivre/ivre/discussions/1495

db2view indexation process seems not being processed with multiple threads, having a big impact in performance, making it impossible to use IVRE to any massive task. Indexing process for some millions is taking weeks to finish (running ivre db2view ). MongoDB seems not be the bottleneck, but IVRE process is using just 1 CPU.

**Comment by merinet** [comment]
Hi,
As workarround to be able search imported data directly at mongodb, instead of waiting to db2view to finish, i've created manually an index at IP Addres:
```
use ivre
db.hosts.createIndex({addr_1:1})
```
To access hosts data at mongodb bypassing IVRE:
`db.hosts.find( { addr_1: Long("xxxxxxxxxxxxxxx") } )`
Now trying to run IVRE in multithreading avoiding GIL using https://github.com/colesbury/nogil

**Comment by p-l-** [comment]
I don't understand. You already have an index, and I don't think you need to "bypass" IVRE. Can you elaborate?

**Comment by merinet** [comment]
Hi Pierre,
As far as i know, until the 'magic' of db2view has been finished i cannot see or retrieve imported scan from IVRE API or dashboard. This task is taking weeks to finish. Did i miss something or did i miss anything?
Regards,

**Comment by p-l-** [comment]
`db2view` has nothing magical! It certainly does not "lock" IVRE and won't prevent you access the data while it processes / creates it. If you can access the data via MongoDB, you can access it via IVRE (again, there is no internal lock)

**Comment by p-l-** [comment]
BTW if you use the `hosts` column, it means you are accessing the "scan" purpose (where results are not merged); you can access it using `ivre scancli` CLI or the `db.nmap.get()` Python API) and not the "view" purpose.
