### ISSUE TITLE
Can you explain to me for me

### ISSUE THREAD

**Issue by why-always-me-mta** [ivre/ivre#1500]
Can you tell me can that I can import  IP data random to scan and view?? If It is possible, how to implement. Thank you

**Comment by p-l-** [comment]
Hi there,

There is a chat that I suppose is more appropriate for this kind of requests. When you have imported a scan (with `ivre scan2db`, you then need to update the view using `ivre db2view`). That's explained in the "principles" part of the documentation: https://doc.ivre.rocks/en/latest/overview/principles.html.

Hope this helps. If you have more questions, join the chat: https://gitter.im/ivre/ivre

**Comment by why-always-me-mta** [comment]
thank you very much
