### ISSUE TITLE
Questions for IVRE!!!

### ISSUE THREAD

**Issue by trungz42k** [ivre/ivre#1503]
I've been using ivre recently (run by docker), as far as I know the command "ivre ipdata --download" is used to download the ip address database from MaxMind, but I don't see any command any guide to scan one or a range of IP addresses. Can I use ivre to scan any range of IP addresses that I want, and how? Hope you help.

**Comment by p-l-** [comment]
Hi, please refer to the documentation (https://doc.ivre.rocks/) and ask specific questions on https://gitter.im/ivre/ivre. Thanks!
