### ISSUE TITLE
I have error when installing Agents

### ISSUE THREAD

**Issue by why-always-me-mta** [ivre/ivre#1508]
![image](https://user-images.githubusercontent.com/74256315/235309455-130c71ed-c4df-4c55-a61f-1b76d4edb9a4.png)

I used Docker to build master, install workers following instructions. But I can't install successfully. I think that problems is ivre runscansagentdb on the “master” can access without password to the agents data directories. Please help me

**Comment by p-l-** [comment]
You probably don't have ssh installed in the container where you run `ivre runscansagentdb`. Please read the logs.

**Comment by why-always-me-mta** [comment]
Now i must install ssh in container master in docker to connect to agent in
other machine, am i???

Vào 05:56, CN, ngày 30 tháng 4 năm 2023 Pierre ***@***.***>
đã viết:
