### ISSUE TITLE
Error when I am building agents

### ISSUE THREAD

**Issue by why-always-me-mta** [ivre/ivre#1511]
I have used Docker as master on Ubuntu, built 1 worker agent on Kali. when on the master run commamd : **ivre runscansagentdb --daemon** , on worker started to run but after  much time but there isn't result,  nmap didn't still run to scan. (I have installed ssh in master to connect remote without password) 
It stopped here: In the in folder input  have data but in the output folder doesn't have data
worker :  ![image](https://user-images.githubusercontent.com/74256315/235725617-e9d13469-ef31-4581-b852-c2f5756ec7de.png)
master:  ![image](https://user-images.githubusercontent.com/74256315/235725696-a2673d89-08ae-4346-9acb-8fc53ce3e60d.png)

Please help me. Is it complete?? Finnally, after scans on workers have completed, they can send data to master??

**Comment by p-l-** [comment]
Again. This is not a forum to ask for help, it is a place to report issues and propose enhancements. Please respect that. You can ask questions on gitter. If nobody answers, it's simply because nobody has enough time for that or they don't want for some reason. Please respect that also.
