### ISSUE TITLE
Error when scan webcam 

### ISSUE THREAD

**Issue by why-always-me-mta** [ivre/ivre#1524]
I am trying to build master-worker agents to scan webcam. I tried IPs but nothing. Can you help me, please? 
![image](https://github.com/ivre/ivre/assets/74256315/462addee-a76a-4c64-92cc-07c257655f19)

**Comment by p-l-** [comment]
Issues are for bug reports. Please stop doing this, after #1500, #1504, #1506, #1508, #1511.

**Comment by why-always-me-mta** [comment]
please explain for me. I don't know IPs are suitable to test to scan for
webcam. Thank you


Vào Th 2, 5 thg 6, 2023 vào lúc 13:54 Pierre ***@***.***>
đã viết:
