### ISSUE TITLE
help me, please

### ISSUE THREAD

**Issue by trungz42k** [ivre/ivre#1528]
I have read your project,docs, It is very perfect . Now, I have problem when classsifing IPs result, I tried to search with web-cam/ geovision/network device but nothing on the dashboad. I linked to Gitter discord and I see that somebody also have problem. What IPs should I test to search results as webcam? Please show me the solution, thank you.

![image](https://github.com/ivre/ivre/assets/114013860/b8d3ac14-2a94-4c83-ab54-643fd644ea6f)
![image](https://github.com/ivre/ivre/assets/114013860/247ae899-aa96-4377-9d88-3993b08e7f34)

**Comment by liverpool-is-the-best** [comment]
I am having problem . I don't know how to specify telephone device or webcam
