### ISSUE TITLE
ivre/client container image has not racluster installed

### ISSUE THREAD

**Issue by guillaume-morel-001** [ivre/ivre#1551]
### IVRE Version

Installed through the docker-composer.yml

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev103-dockerhub

Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

Linux 1252ae9622d7 4.18.0-477.13.1.el8_8.x86_64 #1 SMP Thu May 18 10:27:05 EDT 2023 x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 23.2.0
    PIL: 9.4.0
    bottle: 0.12.25
    cryptography: 41.0.1
    dbus: *missing*
    krbV: *missing*
    matplotlib: *missing*
    psucopg2: *missing*
    pycurl: *missing*
    pymongo: 4.4.0
    sqlalchemy: *missing*
    tinydb: *missing*
```

### Summary

Process fails while trying to load 'flows.argus' into the database

### Expected behavior

The 'flows.argus' data are in the database in order to get them in the WEB interface.

### Actual behavior

The import fails with the following error :
FileNotFoundError: [Errno2] No such file or directory: 'racluster'

### How to reproduce

- Download the ivre-master repository
- Build the container with docker through the 'docker-compose.yml'
- Make some network captures with wireshark (```tshark -w scan-wireshark.pcap -F pcap```) 
- Convert .pcap data into .argus data (```argus -m -r scan-wireshark.pcap -w flows.argus```
- Put the argus data into the ivre/client container (```docker cp flows.argus <ivre/client-id>:/home/scans/```) (ensure to have created previously the /scans repository or choose an other one)
- run ```ivre flow2db flows.argus```

As the installation is from the official ivre repository and images, how can I miss a file ?

### Complete error message
```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/flow2db.py", line 81, in main
    with fileparser(fname, args.pcap_filter) as fdesc:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ivre/parser/argus.py", line 61, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/ivre/parser/__init__.py", line 71, in __init__
    self.proc = subprocess.Popen(cmd, **cmdkargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'racluster'

```

Thanks by advance.

**Comment by p-l-** [comment]
Docker hub images have been updated, you can pull the image again and it should work.

**Comment by guillaume-morel-001** [comment]
> Docker hub images have been updated, you can pull the image again and it should work.

Yes, it solved the issue but highlited and other one. #1553
