### ISSUE TITLE
ivre/client container image has issue in file "/usr/local/lib/python3.11/dist-packages/ivre/db/mongo.py"

### ISSUE THREAD

**Issue by guillaume-morel-001** [ivre/ivre#1553]
Good morning, it's again me with an other issue on the ivre/client docker image.

### Context
Issue #1551 was the previous one I encoutered. Solving it highlighted a new one.

### IVRE Version

Installed through the docker-composer.yml

```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev105-dockerhub

Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

Linux 5445574B4EE0 4.18.0-372.9.1.el8_8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 23.2.0
    PIL: 9.4.0
    bottle: 0.12.25
    cryptography: 41.0.2
    dbus: *missing*
    krbV: *missing*
    matplotlib: *missing*
    psucopg2: *missing*
    pycurl: *missing*
    pymongo: 4.4.1
    sqlalchemy: *missing*
    tinydb: *missing*
```

### Summary

Process fails while trying to load 'flows.argus' into the database

### Expected behavior

The 'flows.argus' data are in the database in order to get them in the WEB interface.

### Actual behavior

The import fails with the following error :
KeyError: 'type' in File "/usr/local/lib/python3.11/dist-packages/ivre/db/mongo.py", line 5775

### How to reproduce

- Download the ivre-master repository
- Build the container with docker through the 'docker-compose.yml'
- Make some network captures with wireshark (```tshark -w scan-wireshark.pcap -F pcap```) 
- Convert .pcap data into .argus data (```argus -m -r scan-wireshark.pcap -w flows.argus```
- Put the argus data into the ivre/client container (```docker cp flows.argus <ivre/client-id>:/home/scans/```) (ensure to have created previously the /scans repository or choose an other one)
- run ```ivre flow2db flows.argus```

### Complete error message
```
root@5445574b4ee0:/home/scans/wireshark# ivre flow2db flows.argus 
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/flow2db.py", line 85, in main
    db.flow.flow2flow(bulk, rec)
  File "/usr/local/lib/python3.11/dist-packages/ivre/db/mongo.py", line 5867, in flow2flow
    findspec = cls._get_flow_key(rec)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ivre/db/mongo.py", line 5775, in _get_flow_key
    key["type"] = rec["type"]
                  ~~~^^^^^^^^
KeyError: 'type'
```

Thanks by advance.

**Comment by p-l-** [comment]
Hi,

Thanks for your report. Could you share a sample `flows.argus` file?

**Comment by guillaume-morel-001** [comment]
Good morning

My file is quite horrific. As I don't achieve to use argus in the docker container ivre/client, I installed it by myself.

Here is the content of my flows.argus :

```
ƒ      åq-Ë            dº™  –‘dº™  ºÁ     <                                                                            ÿÿÿÿ E           ¬ ¬ ÈMD"d¸òñ 	*ñd¸òñ 	-í*<0 ,äTèp’ä                                                                                                                                                                      B ÿÿÿÿÿÿÈMD"{            E           ¬ ¬ ÈMD"d¸òñ 	*ýd¸òñ 	-ö*<0 ,Øžó
Ë                                                                                                                                                                      B  Æ¶ÿ  d¸ó
[...]
ÿ¶ÿ  d¸ó( 
Á_d¸ó( 
Å¹:<0                  d¸ó( 

ôr  þ0  H € òB  ÿÿÿÿÿÿØžó
Ë             ƒ0                      dº™  –‘dº™  Ü     <                          /ø                     Vêä(                    ÿÿÿÿ
```

I tried your solution through an other way, Zeek (with a Zeek container). This way is working pretty well !

**Comment by guillaume-morel-001** [comment]
Of course !

```
[scaner-user@localhost wireshark]$ bzip2 < flow.argus | base64
QlpoOTFBWSZTWWjwQdYFpij/////////////////////////////////////////////4dg0AAAA
AAAAAAAAF71AAAAAAAAAAACAAAAAAAUABu24ADHADx0SElC4AAAAAD33gPI0A8NI98AAAAAAAAAA
AAFgAB0AAAACACAAACIAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAA3wAABM+l
V7ddKubSTQDIKdWwoAAAcADmAAo0NAAAoABXQB0AAAANAAdnwA9oD4ABIASRVRO9nSItsVsuAAAA
AAAAAY6i6AUwqOAAAAAAAAABjp1V7aV3dQ3YDeHHJUVBdVvpo++DHfZ9A6Litm8HOCqSUdA8AAAH
SiDdWNvBzhUEpy0mttiUBGlmn2wJInCyVoZCwxQNBLFTa0kpJZWYrRldmnDYlrVVSsRSwyqqzUPr
R6zy+AAAAAAAAAAAAAAAAAAJ0XrEoj1qS0ACpUAAY2MJfb1z0yDuw7sAAkegaCjR1dg+CFb2HoaA
[...]
```

**Comment by p-l-** [comment]
I need the comprehensive output...

**Comment by guillaume-morel-001** [comment]
> I need the comprehensive output...

I think I won't be able do do better. However I didn't use the argus command integred to IVRE because, it seems that I don't have it.

**Comment by p-l-** [comment]
OK I understand. Without data to reproduce I won't be able to help, sorry.
