### ISSUE TITLE
Installation problems of a noob  

### ISSUE THREAD

**Issue by AntiNubert** [ivre/ivre#1559]
### Version
(IVRE not installed jet, so no version lol.)
Using Linux Mint.

### Summary
 (Uff, I hope I am doing this right...)

I am installing IVRE by the instructions given here: https://doc.ivre.rocks/en/latest/install/fast-install-and-first-run.html

Entered following comand:
$ sudo apt -y --no-install-recommends install mongodb python3-pymongo \
.  >   python3-crypto python3-bottle python3-openssl apache2 \
.  >   libapache2-mod-wsgi-py3 dokuwiki

### Expected behavior

Not specified by the website, apparently no output should show.

### Actual behavior

$ sudo apt -y --no-install-recommends install mongodb python3-pymongo \
 . >   python3-crypto python3-bottle python3-openssl apache2 \
 . >   libapache2-mod-wsgi-py3 dokuwiki

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Package 'mongodb' has no installation candidate

### How to reproduce

Just following the instructions on website.

### More

Atempted to install mongodb the following way:  (As instructed here: https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/)
$ sudo touch /etc/apt/sources.list.d/mongodb-org-6.0.list
$ ls
Desktop                              Music           Templates
Documents                            Pictures        Videos
Downloads                            Public          Warpinator
libapache2-mod-wsgi-py3              python3-crypto
libssl1.1_1.1.1f-1ubuntu2_amd64.deb  rtl8852be
$ sudo apt-get update
(worked fine)
$ sudo apt-get install -y mongodb-org
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mongodb-org is already the newest version (6.0.8).
0 to upgrade, 0 to newly install, 0 to remove and 49 not to upgrade.
$ ps --no-headers -o comm 1
systemd
$ sudo systemctl start mongod
$ 
mongosh
Current Mongosh Log ID:	64ca1eea066325ac3955c3d3
Illegal instruction (core dumped)

//////////

Installed pymongo just fine.

**Comment by p-l-** [comment]
Hi there!

You need to install MongoDB. For more on how to do so on your distribution, please refer to MongoDB's documentation.

**Comment by AntiNubert** [comment]
Yes, I know so much, but as you see, I already did install Mongodb, I apperantly just did something wrong.
