### ISSUE TITLE
Error in detecting device types

### ISSUE THREAD

**Issue by chriseriksen** [ivre/ivre#1560]
Hi sir,
I have built successfully IVRE to detect webcams by searching data from Shodan. But now, I want to detect phones. I tried to scan PBX/ voIP phones but It failed.
I have a question: "What kinds of phone that IVRE can detect and how to get data to scan?"
I am looking forward from hearing from you.
Thank you vary much

**Comment by p-l-** [comment]
Hi there,
Thanks for your interest in IVRE. IVRE only uses the `devicetype` attribute of the `service` detected by Nmap. So it entirely depends on Nmap, and your question should be asked to the Nmap project.
Happy hacking!
