### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by AntiNubert** [ivre/ivre#1561]
### IVRE Version

Still to be installed

### Summary

Currently installing IVRE following these instructions: https://doc.ivre.rocks/en/latest/install/fast-install-and-first-run.html
After the instructions on the official website to installing mongodb seemed outdated, I found a different method to install it.
This rendered a problematic part of the install instructions redundant, or so I hope:

sudo apt -y --no-install-recommends install mongodb python3-pymongo \
.   >   python3-crypto python3-bottle python3-openssl apache2 \
.   >   libapache2-mod-wsgi-py3 dokuwiki 

This did not work for me, so I installed mongodb another way.
It seems to be installed correctly. 

Remaining Install  instructions worked just fine.

The problem shows at the second step of the "setup" instructions:

# cd /var/www/html ## or depending on your version /var/www

### Expected behavior

Moving to the folder described above.

### Actual behavior

bash: cd: /var/www/html: No such file or directory

alternatively:

bash: cd: /var/www: No such file or directory

### More

So apparently the folder was not created. My assumption is that it was part of the step I skipped, or maybe a new version with a new foldername was released.

Can anyone help me?

**Comment by p-l-** [comment]
You need to re-run the step `sudo apt -y --no-install-recommends install python3-pymongo python3-crypto python3-bottle python3-openssl apache2 libapache2-mod-wsgi-py3 dokuwiki` (without mongodb since you installed it otherwise on your system).
