### ISSUE TITLE
Problem in config

### ISSUE THREAD

**Issue by chriseriksen** [ivre/ivre#1567]
Hi sir, 
I have built IVRE by using Docker to build server-agent to scan following docs. Now, I want to adjust GUI but still remain database. Is it possible?? When i download and install using Docker in project, can I adjust config GUI ??
Please write me some notes.
Thank you very much.

**Comment by p-l-** [comment]
I don't understand. What do you want to do when you say "adjust GUI"? Change the code of the Web interface?

**Comment by chriseriksen** [comment]
> I don't understand. What do you want to do when you say "adjust GUI"? Change the code of the Web interface?
Yes. I only want to concenstrate on scaning and detecting device types, I want to  eliminate some button that is not related. 
I built IVRE by downloading and using Docker to build following documentation. I tried to read and fix code in folder ivre/docker . Is it possilbe??
Thank you very much

**Comment by p-l-** [comment]
Oh OK. In that case, you must either use IVRE without Docker or build your own, modified Docker images.

Happy hacking (and to forget to submit your changes as pull requests if you think they can be useful to others!)
