### ISSUE TITLE
Problem in heatmap

### ISSUE THREAD

**Issue by chriseriksen** [ivre/ivre#1569]
Hi sir,
I have built successfully IVRE on my computer. After scanning data, I have a problem. It seems that heat map is too small, difficult in observing. I 've tried to fix in https://github.com/ivre/ivre/blob/master/web/static/ivre/graph.js but doesn't have changes. Can you show me sollutons to enlarge heat map or change color to dintinguish near country?
![image](https://github.com/ivre/ivre/assets/141014375/9787a1d1-e80f-48d3-a964-f454f52e4e53)

Thank you very much

**Comment by p-l-** [comment]
You can add a filter on country (e.g., `country:US`) and then click "Map" again: you'd get a map centred on your data. Is that helpful or did I misunderstand your question?

**Comment by chriseriksen** [comment]
I am concenstating on scanning device type as phones/webcam. Now, I want to observe heat map of total countries but it seems too small, It's difficult in dinstinguishing among countries. Can you show me how to enlarge map or change color between near country to observe easily??
Thank you very much

**Comment by p-l-** [comment]
There is no way to enlarge the map in the UI. But since it's a vector image (SVG) maybe you can just download it and open it in a tool such as Inkscape (or Gimp if you want to convert it to a pixel image).
