### ISSUE TITLE
how to  recover nmap data 

### ISSUE THREAD

**Issue by sanpichen** [ivre/ivre#1571]
Please try to follow this template. Also, please format your issue
properly (particularly to report code or command line output). You may
want to read
[Github's basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/).

### IVRE Version

Insert here the output of the command `ivre version`, displayed as
code. For example:

```
$ ivre version
root@ffedef202663:/ivre-share# ivre --version
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18.dev5-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Linux ffedef202663 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing
```

### Summary

I would like to recovery data after "ivre scancli  -c NET-CAMPAIGN-20230720-1000  --delete"

### Expected behavior
data imported again , command "scan2db、db2view" successfully
 
### Actual behavior

If needed, describe what actually happens. Be sure to include
comprehensive output, including obscure error messages, logs from the
Web or DB server if appropriate, etc.

### How to reproduce
nmap periodically  and scan2db with categories  named "...NET-CAMPAIGN-20230520-1000、NET-CAMPAIGN-20230620-1000、NET-CAMPAIGN-20230720-1000、NET-CAMPAIGN-20230820-1000...”

ivre scancli  --category NET-CAMPAIGN-20230720-1000  --delete

###made  misstake ,try to recover!!

root@ffedef202663:/ivre-share# ivre scan2db -c NET-CAMPAIGN-20230720-1000 -s ivre -r /ivre-share/20230720-1000/scans/RANGE-*/up
INFO:ivre:0 results imported.  ###no way？

### More

Please include any other information that could help us, including
scan results or PCAP samples. We will be able to help you faster if we
don't have to ask questions and wait for your answers.

**Comment by p-l-** [comment]
There is no recovery option after `--delete`. More recent development versions of IVRE can import a file more than once and may be a solution for you.
