### ISSUE TITLE
Problem in storing database

### ISSUE THREAD

**Issue by chriseriksen** [ivre/ivre#1575]
I've built IVRE to scan and store data using MongoDB. I have a quetion:"What is the biggest size of data IVRE can store? How does IVRE do to store big data?"The last question I think it's vey silly but I can't find where database is built. Please help me 
Thank you very much

**Comment by p-l-** [comment]
The (default) backend database is MongoDB. So your question is "What is the biggest size of data MongoDB can store", and that's a question for the MongoDB project!
