### ISSUE TITLE
ValueError: Unknown file type /var/lib/ivre/master/output/651d6f07aeb2/651d6f07aeb2/3j24k2.xml

### ISSUE THREAD

**Issue by gitingua** [ivre/ivre#1595]
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 698cff935c

Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]

Linux hostname 5.4.0-163-generic #180-Ubuntu SMP Tue Sep 5 13:21:23 UTC 2023 x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 19.0.0
    PIL: 10.0.1
    bottle: 0.12.15
    cryptography: 2.8
    dbus: 1.2.16
    krbV: *missing*
    matplotlib: 3.7.3
    psycopg2: *missing*
    pycurl: *missing*
    pymongo: 3.10.1
    sqlalchemy: *missing*
    tinydb: *missing*
    elasticsearch: *missing*
    elasticsearch_dsl: *missing*

Error add scan ivre master and agent 

-----------------------------master ivre
root@host:$ ivre runscansagentdb --add-local-master

root@host:$ ivre runscansagentdb --source MySource --add-agent root@scan-host:~/agent-data

root@host:$ ivre runscansagentdb --list-agents
agent:
  - id: 651d9df07aeb2
  - source name: MySource
  - remote host: root@scan-host
  - remote path: ~/agent-data/
  - master: 651d641275bf6f25080b867b
  - local path: /var/lib/ivre/master/aa0kwvyk
  - rsync command: rsync
  - current scan: None
  - currently synced: True
  - max waiting targets: 60
  - waiting targets: 0
  - current targets: 0
  - can receive: 60

root@host:$ ivre runscansagentdb --assign-free-agents --routable --limit 1 --range 127.0.0.1 127.0.0.1

root@host:$ ivre runscansagentdb --list-scans
scan:
  - id: 651d6f07aeb2
  - categories:
    - RANGE-127.0.0.1-127.0.0.1
  - targets added: 0
  - results fetched: 0
  - total targets to add: 1
  - available targets: 1
  - internal state: (0, 1, 1, 0)
  - agents:
    - 651d9df07aeb2

root@host:$ ivre runscansagentdb --daemon
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2244, in store_scan
    store_scan_function = {
KeyError: b'N'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.8/dist-packages/ivre/tools/runscansagentdb.py", line 264, in main
    ivre.db.db.agent.sync_all(masterid)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 4467, in sync_all
    self.sync(agentid)
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 4524, in sync
    self.globaldb.nmap.store_scan(
  File "/usr/local/lib/python3.8/dist-packages/ivre/db/__init__.py", line 2293, in store_scan
    raise ValueError(  # pylint: disable=raise-missing-from
ValueError: Unknown file type /var/lib/ivre/master/output/651d6425f98759c7aaad3854/651d6419069d6f59df07aeb2/5v6dhf06.xml

agent iver 
[root@scan-host agent-data]# ./agent
[master     ] spawning 10 workers
[worker 1   ] worker ready
[worker 2   ] worker ready
[worker 4   ] worker ready
[worker 5   ] worker ready
[worker 3   ] worker ready
[worker 6   ] worker ready
[worker 8   ] worker ready
[worker 7   ] worker ready
[worker 9   ] worker ready
[worker 10  ] worker ready
[worker 2   ] scan 651d6f07aeb2-u9d6pbua
[worker 2   ] nmap: unrecognized option '--script-timeout'
[worker 2   ] done 651d6f07aeb2-u9d6pbua

**Comment by p-l-** [comment]
Hi there,

Thanks for your report. I'd need the result file to understand what happened here.

**Comment by gitingua** [comment]
@p-l- 
I'm still figuring out ivre
Can you tell me where this file is located?

**Comment by p-l-** [comment]
`/var/lib/ivre/master/output/651d6425f98759c7aaad3854/651d6419069d6f59df07aeb2/5v6dhf06.xml` I suppose, from the error message? If it's no longer here, maybe try a something like `/var/lib/ivre/master/error`?

**Comment by gitingua** [comment]
@p-l- 
maybe I was using an old version of nmap on the agent and that could have caused the error nmap 6.80 

on another agent where version 7.80 is installed
there is no such error
but I'm running a scan on 127.0.0.1
but it does not write the result and freezes

Sorry for so many questions and thank you for answering


now 
AGENT

[worker 2   ] scan 651dbd4e4870-rhhwvrfo
[worker 2   ] sendto in send_ip_packet_sd: sendto(33, packet, 65536, 0, 127.0.0.1, 16) => Message too long
[worker 2   ] Offending packet: TCP 127.0.0.1:45502 > 127.0.0.1:22 S ttl=128 id=0 iplen=0  seq=500346988 win=3072 <mss 1460>
[worker 2   ] done 651dbd4e4870-rhhwvrfo

and stops there.

there is no file with the results on either the master or the agent

master 
ivre runscansagentdb --assign-free-agents --routable --limit 1 --range 127.0.0.1 127.0.0.1 ^C
ivre runscansagentdb --daemon

**Comment by p-l-** [comment]
You seem to have an Nmap error, so that's more a question for the Nmap project I guess. And yes, Nmap 6.80 is too old!
