### ISSUE TITLE
WebUi won't show up

### ISSUE THREAD

**Issue by TTVNaylek** [ivre/ivre#1671]
### IVRE Version
```
$ ivre version      
/usr/local/bin/ivre:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('ivre==0.9.21.dev10', 'ivre')
IVRE - Network recon framework
Copyright 2011 - 2024 Pierre LALET <pierre@droids-corp.org>
Version 0.9.21.dev10

Python 3.12.6 (main, Sep  7 2024, 14:20:15) [GCC 14.2.0]

Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64

Dependencies:
    MySQLdb: 1.4.6
    OpenSSL: 24.2.1
    PIL: 10.4.0
    bottle: 0.12.25
    cryptography: 43.0.0
    dbus: 1.3.2
    krbV: *missing*
    matplotlib: 3.8.3
    psycopg2: 2.9.9 (dt dec pq3 ext lo64)
    pycurl: PycURL/7.45.3 libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.63.0 librtmp/2.3 OpenLDAP/2.5.18
    pymongo: 4.10.1
    sqlalchemy: 2.0.32
    tinydb: 3.15.2
    elasticsearch: 7.17.6
    elasticsearch_dsl: *missing*
```

### Actual behavior
Hello, I installed IVRE on my Kali Linux machine to test the tool as it intrigued me greatly.

The installation was done without any problem but when I want to access the Web interface as there is in the site that allows to follow the installation but there is nothing.

I don't know if I've done something wrong but I hope someone can help me.

### How to reproduce

On kali linux:
sudo apt update && sudo apt install ivre

On browser:
http://localhost/

### More
Website link: [https://doc.ivre.rocks/en/latest/install/fast-install-and-first-run.html](url)

![image](https://github.com/user-attachments/assets/d49fb672-d267-4cc6-804a-273dc1a1721c)
![image](https://github.com/user-attachments/assets/536f7664-1399-4627-88a2-e2b2b4f0145d)
![image](https://github.com/user-attachments/assets/3fdb0413-b439-471f-9ab6-a96bbdd78fb4)

**Comment by p-l-** [comment]
Did you start the web server? You either need to configure Nginx or Apache, or to use `ivre httpd`.
