### ISSUE TITLE
I have error in import nuclei scan result

### ISSUE THREAD

**Issue by arsenalliverpool** [ivre/ivre#1672]
![image](https://github.com/user-attachments/assets/d6241823-605c-4149-856c-108d5b338315)
when i try to add json result from nuclei from  but it report error such status, port.
In nuclei, i use command:  nuclei -u 113.161.250.157 -json-export nuclei/result.json
Please help me. Thank you

**Comment by p-l-** [comment]
There's an issue template for a reason, we need to know at least the version of IVRE you are using.

**Comment by arsenalliverpool** [comment]
![image](https://github.com/user-attachments/assets/279d107a-e381-4f26-98ef-9c484847a713)
Please help me. Thank you

**Comment by p-l-** [comment]
Can you share the output file you are trying to import and the version of Nuclei you are using.

**Comment by arsenalliverpool** [comment]
I run command: nuclei -u 113.161.250.157 -json-export nuclei/result.json
I am using nuceli :
![image](https://github.com/user-attachments/assets/d3d5740f-c324-4fc0-9ec5-2702b0ce5a2f)

**Comment by p-l-** [comment]
And with this result file, can you check again that you have the exact error mentioned in the issue?

**Comment by arsenalliverpool** [comment]
I only rename file result name on the pictture that I sent you. I imported result.json but this error still existed!!! 
Please help me

**Comment by p-l-** [comment]
I don't have the same error than yours. So please as a first step, can you update to the current version and try again, then report the error you have?

**Comment by arsenalliverpool** [comment]
sorry, but i don't know how to update IVRE!! Please show me, thank you sir

**Comment by p-l-** [comment]
OK and now we both have the same error (see the error is different from the original one?)!

So I think IVRE is expecting JSONL (new-line delimited JSON documents) rather than JSON. Can you try with `-jsonl-export` rather than `-json-export`?

**Comment by arsenalliverpool** [comment]
Perfect!!!. Thanks sir very much

**Comment by p-l-** [comment]
I'm not sure to understand your question but anyway I'll close this issue.
