### ISSUE TITLE
Documentation for YETI

### ISSUE THREAD

**Issue by Mattberruet** [ivre/ivre#1683]
Hello,

I have been using IVRE for a while now, and I would like to combine it with YETI. Could you provide documentation to help set it up?

Best regards,

**Comment by p-l-** [comment]
Hi,
I'm no longer using Yeti (at least, for now) so I won't really be able to help. However, the [documentation](https://github.com/yeti-platform/yeti/tree/main/contrib/analytics/ivre_api) should be enough to get you started. If you have specific questions, feel free to ask them (in an issue here or on the Yeti repository, depending on the question).
