### ISSUE TITLE
Wishlist for the web interface

### ISSUE THREAD

**Issue by trou** [ivre/ivre#791]
Hi,
it would be nice to have the following features for the web interface:

- [x] raw IP list text export: the ability to export the list of matching IPs as a simple list, copy pastable
- [ ] a "full text search" operator, which could work like `banner:` but across all fields. It'd be particularly useful when some machines report, for example their product name, some string across a variety of services.

**Comment by p-l-** [comment]
Thanks for the suggestions!

While the first one is probably easy to implement, the second one is probably much harder, particularly with the MongoDB backend.
